[package]
name = "miso_record"
edition = "2024"
license = "Apache-2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { git = "https://github.com/misofm/protocol.git", rev = "09f0dc699a112c37d8da8a765596cc1ed623fe79" }
