[package]
name = "miso_record_access"
edition = "2024"
license = "Apache-2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { local = "../../../miso-protocol/move" }
miso_record = { local = "../../move" }
